import Head from "next/head";
import Image from "next/image";
import styles from "../Home.module.scss";
import React, { useState } from "react";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Вариклечко</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="../img/variklechko.png" />
				<link rel="preconnect" href="https://app.snipcart.com" />
				<link rel="preconnect" href="https://cdn.snipcart.com" />
				<link
					rel="stylesheet"
					href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css"
				/>
				<link
					href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
					rel="stylesheet"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Lato&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<div className={styles.nav_top}>
				<a className="active" href="../">
					<img src="../img/variklechko.png" />
				</a>
				<a href="../">
					<h1>ВАРИКЛЕЧКО</h1>
				</a>
				<input
					className={styles.searchBox}
					type="text"
					id="searchBox"
					placeholder="Търси артикул ..."
					enterkeyhint="search"
				/>

				<a className={styles.nav_top_button} href="/src/pages/components/wishlist">
					Wishlist
				</a>
				<a className={styles.nav_top_button} href="/src/pages/components/contact">
					Contact
				</a>
				<a className={styles.nav_top_button} onClick="">
					Login
				</a>
			</div>
			<div className={styles.nav_category}>
				<ul className={styles.nav_category}>
					<li className={styles.nav_category_button}>
						<a href="../categories/hardware">Hardware</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Phone">Phone</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Video">Video, Photo & TV</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Audio">Audio & HiFi</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Home">Home</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Pharmacy">Pharmacy</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Sports">Sports & Freetime</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Diy">DIY & Garden</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Car">Car & Motorcycle</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Toy">Toy & Model Making</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Games">Games</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Movies">Movies</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Software">Software</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Office">Office & School</a>
					</li>
					<li className={styles.nav_category_button}>
						<a href="../categories/Services">Services</a>
					</li>
				</ul>
			</div>

			<div className={styles.wishlist}>
				<h1>Your Wish List</h1>
				<input
					type="text"
					name="wish"
					placeholder="Create a new wish"
					required
					maxlength="25"
				/>
				<input type="submit" value="Send" />
				<ul></ul>
			</div>
		</div>
	);
}
